# Generated by Django 4.0.3 on 2022-10-31 19:10

from django.db import migrations,models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Usuario',
            name='escolaridade',
            field= models.CharField(max_length=45),
            preserve_default=True
        ),
    ]
