# Generated by Django 4.0.3 on 2022-12-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountable',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.institution'),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='institution',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.institution'),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='voluntary',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.voluntary'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.address', verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='phoneinstitution',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.institution'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='escolaridade',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='voluntary',
            name='institution',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.institution'),
        ),
    ]
